/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * Response model for adding a file to a collection.
 * 
 * Returns the updated collection containing the newly added file
 * along with any generated metadata.
 * @export
 * @interface AddFileResponse
 */
export interface AddFileResponse {
    /**
     * 
     * @type {Collection}
     * @memberof AddFileResponse
     */
    collection: Collection;
}

/**
 * Check if a given object implements the AddFileResponse interface.
 */
export function instanceOfAddFileResponse(value: object): value is AddFileResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function AddFileResponseFromJSON(json: any): AddFileResponse {
    return AddFileResponseFromJSONTyped(json, false);
}

export function AddFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': CollectionFromJSON(json['collection']),
    };
}

export function AddFileResponseToJSON(json: any): AddFileResponse {
    return AddFileResponseToJSONTyped(json, false);
}

export function AddFileResponseToJSONTyped(value?: AddFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionToJSON(value['collection']),
    };
}

