/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a single address suggestion.
 * @export
 * @interface AddressSuggestion
 */
export interface AddressSuggestion {
    /**
     * The full suggested address text
     * @type {string}
     * @memberof AddressSuggestion
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof AddressSuggestion
     */
    placeId?: string | null;
}

/**
 * Check if a given object implements the AddressSuggestion interface.
 */
export function instanceOfAddressSuggestion(value: object): value is AddressSuggestion {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function AddressSuggestionFromJSON(json: any): AddressSuggestion {
    return AddressSuggestionFromJSONTyped(json, false);
}

export function AddressSuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressSuggestion {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'placeId': json['place_id'] == null ? undefined : json['place_id'],
    };
}

export function AddressSuggestionToJSON(json: any): AddressSuggestion {
    return AddressSuggestionToJSONTyped(json, false);
}

export function AddressSuggestionToJSONTyped(value?: AddressSuggestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'place_id': value['placeId'],
    };
}

