/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressSuggestion } from './AddressSuggestion';
import {
    AddressSuggestionFromJSON,
    AddressSuggestionFromJSONTyped,
    AddressSuggestionToJSON,
    AddressSuggestionToJSONTyped,
} from './AddressSuggestion';

/**
 * Response model for address autocomplete suggestions.
 * @export
 * @interface AddressAutocompleteResponse
 */
export interface AddressAutocompleteResponse {
    /**
     * 
     * @type {Array<AddressSuggestion>}
     * @memberof AddressAutocompleteResponse
     */
    suggestions: Array<AddressSuggestion>;
}

/**
 * Check if a given object implements the AddressAutocompleteResponse interface.
 */
export function instanceOfAddressAutocompleteResponse(value: object): value is AddressAutocompleteResponse {
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    return true;
}

export function AddressAutocompleteResponseFromJSON(json: any): AddressAutocompleteResponse {
    return AddressAutocompleteResponseFromJSONTyped(json, false);
}

export function AddressAutocompleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressAutocompleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestions': ((json['suggestions'] as Array<any>).map(AddressSuggestionFromJSON)),
    };
}

export function AddressAutocompleteResponseToJSON(json: any): AddressAutocompleteResponse {
    return AddressAutocompleteResponseToJSONTyped(json, false);
}

export function AddressAutocompleteResponseToJSONTyped(value?: AddressAutocompleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestions': ((value['suggestions'] as Array<any>).map(AddressSuggestionToJSON)),
    };
}

