/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Agent } from './Agent';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent';

/**
 * Response model for listing agents.
 * @export
 * @interface AgentListResponse
 */
export interface AgentListResponse {
    /**
     * List of agents
     * @type {Array<Agent>}
     * @memberof AgentListResponse
     */
    agents: Array<Agent>;
}

/**
 * Check if a given object implements the AgentListResponse interface.
 */
export function instanceOfAgentListResponse(value: object): value is AgentListResponse {
    if (!('agents' in value) || value['agents'] === undefined) return false;
    return true;
}

export function AgentListResponseFromJSON(json: any): AgentListResponse {
    return AgentListResponseFromJSONTyped(json, false);
}

export function AgentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agents': ((json['agents'] as Array<any>).map(AgentFromJSON)),
    };
}

export function AgentListResponseToJSON(json: any): AgentListResponse {
    return AgentListResponseToJSONTyped(json, false);
}

export function AgentListResponseToJSONTyped(value?: AgentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agents': ((value['agents'] as Array<any>).map(AgentToJSON)),
    };
}

