/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of different agent types.
 * 
 * This enum defines the various types of agents that can be created,
 * such as Knowledge Base Agents and REST API Agents.
 * @export
 */
export const AgentTypes = {
    KnowledgeBase: 'Knowledge Base',
    RestApi: 'REST API',
    AmazonAthena: 'Amazon Athena',
    Unknown: 'Unknown'
} as const;
export type AgentTypes = typeof AgentTypes[keyof typeof AgentTypes];


export function instanceOfAgentTypes(value: any): boolean {
    for (const key in AgentTypes) {
        if (Object.prototype.hasOwnProperty.call(AgentTypes, key)) {
            if (AgentTypes[key as keyof typeof AgentTypes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentTypesFromJSON(json: any): AgentTypes {
    return AgentTypesFromJSONTyped(json, false);
}

export function AgentTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTypes {
    return json as AgentTypes;
}

export function AgentTypesToJSON(value?: AgentTypes | null): any {
    return value as any;
}

export function AgentTypesToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentTypes {
    return value as AgentTypes;
}

