/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of possible assessment statuses for items, collections, and verification jobs.
 * 
 * Represents the current state of evaluation for various entities in the system,
 * tracking progress from initial submission through final approval or rejection.
 * @export
 */
export const AssessmentStatus = {
    Pending: 'Pending',
    Assessing: 'Assessing',
    Approved: 'Approved',
    Rejected: 'Rejected',
    NeedsReview: 'Needs Review',
    Error: 'Error'
} as const;
export type AssessmentStatus = typeof AssessmentStatus[keyof typeof AssessmentStatus];


export function instanceOfAssessmentStatus(value: any): boolean {
    for (const key in AssessmentStatus) {
        if (Object.prototype.hasOwnProperty.call(AssessmentStatus, key)) {
            if (AssessmentStatus[key as keyof typeof AssessmentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssessmentStatusFromJSON(json: any): AssessmentStatus {
    return AssessmentStatusFromJSONTyped(json, false);
}

export function AssessmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentStatus {
    return json as AssessmentStatus;
}

export function AssessmentStatusToJSON(value?: AssessmentStatus | null): any {
    return value as any;
}

export function AssessmentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AssessmentStatus {
    return value as AssessmentStatus;
}

