/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TotalCheckResponse } from './TotalCheckResponse';
import {
    TotalCheckResponseFromJSON,
    TotalCheckResponseFromJSONTyped,
    TotalCheckResponseToJSON,
    TotalCheckResponseToJSONTyped,
} from './TotalCheckResponse';
import type { TokenUsage } from './TokenUsage';
import {
    TokenUsageFromJSON,
    TokenUsageFromJSONTyped,
    TokenUsageToJSON,
    TokenUsageToJSONTyped,
} from './TokenUsage';

/**
 * Response model for the call_using_all_files function
 * @export
 * @interface CallUsingAllFilesResponse
 */
export interface CallUsingAllFilesResponse {
    /**
     * 
     * @type {TotalCheckResponse}
     * @memberof CallUsingAllFilesResponse
     */
    response: TotalCheckResponse;
    /**
     * 
     * @type {TokenUsage}
     * @memberof CallUsingAllFilesResponse
     */
    tokenUsage: TokenUsage;
}

/**
 * Check if a given object implements the CallUsingAllFilesResponse interface.
 */
export function instanceOfCallUsingAllFilesResponse(value: object): value is CallUsingAllFilesResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('tokenUsage' in value) || value['tokenUsage'] === undefined) return false;
    return true;
}

export function CallUsingAllFilesResponseFromJSON(json: any): CallUsingAllFilesResponse {
    return CallUsingAllFilesResponseFromJSONTyped(json, false);
}

export function CallUsingAllFilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallUsingAllFilesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': TotalCheckResponseFromJSON(json['response']),
        'tokenUsage': TokenUsageFromJSON(json['token_usage']),
    };
}

export function CallUsingAllFilesResponseToJSON(json: any): CallUsingAllFilesResponse {
    return CallUsingAllFilesResponseToJSONTyped(json, false);
}

export function CallUsingAllFilesResponseToJSONTyped(value?: CallUsingAllFilesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': TotalCheckResponseToJSON(value['response']),
        'token_usage': TokenUsageToJSON(value['tokenUsage']),
    };
}

