/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionFileItemInstance } from './CollectionFileItemInstance';
import {
    CollectionFileItemInstanceFromJSON,
    CollectionFileItemInstanceFromJSONTyped,
    CollectionFileItemInstanceToJSON,
    CollectionFileItemInstanceToJSONTyped,
} from './CollectionFileItemInstance';

/**
 * Extended file model that includes assessment results against multiple item instances.
 * 
 * Inherits from CollectionFile and adds tracking of how the file performs
 * against various item criteria through file_checks.
 * @export
 * @interface CollectionFileInstance
 */
export interface CollectionFileInstance {
    /**
     * 
     * @type {string}
     * @memberof CollectionFileInstance
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileInstance
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileInstance
     */
    s3Key: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileInstance
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileInstance
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileInstance
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileInstance
     */
    size?: number | null;
    /**
     * 
     * @type {Array<CollectionFileItemInstance>}
     * @memberof CollectionFileInstance
     */
    fileChecks?: Array<CollectionFileItemInstance>;
}

/**
 * Check if a given object implements the CollectionFileInstance interface.
 */
export function instanceOfCollectionFileInstance(value: object): value is CollectionFileInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    return true;
}

export function CollectionFileInstanceFromJSON(json: any): CollectionFileInstance {
    return CollectionFileInstanceFromJSONTyped(json, false);
}

export function CollectionFileInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFileInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['created_at'],
        's3Key': json['s3_key'],
        'description': json['description'] == null ? undefined : json['description'],
        'contentType': json['content_type'],
        'filename': json['filename'],
        'size': json['size'] == null ? undefined : json['size'],
        'fileChecks': json['file_checks'] == null ? undefined : ((json['file_checks'] as Array<any>).map(CollectionFileItemInstanceFromJSON)),
    };
}

export function CollectionFileInstanceToJSON(json: any): CollectionFileInstance {
    return CollectionFileInstanceToJSONTyped(json, false);
}

export function CollectionFileInstanceToJSONTyped(value?: CollectionFileInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'],
        's3_key': value['s3Key'],
        'description': value['description'],
        'content_type': value['contentType'],
        'filename': value['filename'],
        'size': value['size'],
        'file_checks': value['fileChecks'] == null ? undefined : ((value['fileChecks'] as Array<any>).map(CollectionFileItemInstanceToJSON)),
    };
}

