/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionFileStatus } from './CollectionFileStatus';
import {
    CollectionFileStatusFromJSON,
    CollectionFileStatusFromJSONTyped,
    CollectionFileStatusToJSON,
    CollectionFileStatusToJSONTyped,
} from './CollectionFileStatus';

/**
 * Represents the assessment result of a collection file against a specific item instance.
 * 
 * This model tracks how a particular file performs against item criteria, including
 * status, reasoning, address matching, and associated costs from AI processing.
 * @export
 * @interface CollectionFileItemInstance
 */
export interface CollectionFileItemInstance {
    /**
     * 
     * @type {CollectionFileStatus}
     * @memberof CollectionFileItemInstance
     */
    status?: CollectionFileStatus | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileItemInstance
     */
    statusReasoning?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileItemInstance
     */
    itemInstanceId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionFileItemInstance
     */
    addressMatch?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionFileItemInstance
     */
    detectedAddress?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileItemInstance
     */
    cost?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileItemInstance
     */
    inputTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileItemInstance
     */
    outputTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CollectionFileItemInstance
     */
    clusterNumber?: number | null;
}



/**
 * Check if a given object implements the CollectionFileItemInstance interface.
 */
export function instanceOfCollectionFileItemInstance(value: object): value is CollectionFileItemInstance {
    if (!('itemInstanceId' in value) || value['itemInstanceId'] === undefined) return false;
    return true;
}

export function CollectionFileItemInstanceFromJSON(json: any): CollectionFileItemInstance {
    return CollectionFileItemInstanceFromJSONTyped(json, false);
}

export function CollectionFileItemInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFileItemInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : CollectionFileStatusFromJSON(json['status']),
        'statusReasoning': json['status_reasoning'] == null ? undefined : json['status_reasoning'],
        'itemInstanceId': json['item_instance_id'],
        'addressMatch': json['address_match'] == null ? undefined : json['address_match'],
        'detectedAddress': json['detected_address'] == null ? undefined : json['detected_address'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'inputTokens': json['input_tokens'] == null ? undefined : json['input_tokens'],
        'outputTokens': json['output_tokens'] == null ? undefined : json['output_tokens'],
        'clusterNumber': json['cluster_number'] == null ? undefined : json['cluster_number'],
    };
}

export function CollectionFileItemInstanceToJSON(json: any): CollectionFileItemInstance {
    return CollectionFileItemInstanceToJSONTyped(json, false);
}

export function CollectionFileItemInstanceToJSONTyped(value?: CollectionFileItemInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': CollectionFileStatusToJSON(value['status']),
        'status_reasoning': value['statusReasoning'],
        'item_instance_id': value['itemInstanceId'],
        'address_match': value['addressMatch'],
        'detected_address': value['detectedAddress'],
        'cost': value['cost'],
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
        'cluster_number': value['clusterNumber'],
    };
}

