/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * Response model for retrieving a single collection.
 * 
 * Returns detailed information about a specific collection including
 * all associated files, items, and metadata.
 * @export
 * @interface CollectionResponse
 */
export interface CollectionResponse {
    /**
     * 
     * @type {Collection}
     * @memberof CollectionResponse
     */
    collection: Collection;
}

/**
 * Check if a given object implements the CollectionResponse interface.
 */
export function instanceOfCollectionResponse(value: object): value is CollectionResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function CollectionResponseFromJSON(json: any): CollectionResponse {
    return CollectionResponseFromJSONTyped(json, false);
}

export function CollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': CollectionFromJSON(json['collection']),
    };
}

export function CollectionResponseToJSON(json: any): CollectionResponse {
    return CollectionResponseToJSONTyped(json, false);
}

export function CollectionResponseToJSONTyped(value?: CollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionToJSON(value['collection']),
    };
}

