/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a file within a collection that needs to be assessed.
 * 
 * Contains metadata about uploaded files including S3 storage information,
 * content type, and optional descriptive information.
 * @export
 * @interface CollectionFile
 */
export interface CollectionFile {
    /**
     * 
     * @type {string}
     * @memberof CollectionFile
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionFile
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionFile
     */
    s3Key: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionFile
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionFile
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionFile
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionFile
     */
    size?: number | null;
}

/**
 * Check if a given object implements the CollectionFile interface.
 */
export function instanceOfCollectionFile(value: object): value is CollectionFile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    return true;
}

export function CollectionFileFromJSON(json: any): CollectionFile {
    return CollectionFileFromJSONTyped(json, false);
}

export function CollectionFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['created_at'],
        's3Key': json['s3_key'],
        'description': json['description'] == null ? undefined : json['description'],
        'contentType': json['content_type'],
        'filename': json['filename'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function CollectionFileToJSON(json: any): CollectionFile {
    return CollectionFileToJSONTyped(json, false);
}

export function CollectionFileToJSONTyped(value?: CollectionFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'],
        's3_key': value['s3Key'],
        'description': value['description'],
        'content_type': value['contentType'],
        'filename': value['filename'],
        'size': value['size'],
    };
}

