/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model containing presigned URLs for collection files.
 * @export
 * @interface CollectionFilePresignedUrlsResponse
 */
export interface CollectionFilePresignedUrlsResponse {
    /**
     * Dictionary mapping file IDs to their presigned GET URLs
     * @type {{ [key: string]: string; }}
     * @memberof CollectionFilePresignedUrlsResponse
     */
    presignedUrls: { [key: string]: string; };
}

/**
 * Check if a given object implements the CollectionFilePresignedUrlsResponse interface.
 */
export function instanceOfCollectionFilePresignedUrlsResponse(value: object): value is CollectionFilePresignedUrlsResponse {
    if (!('presignedUrls' in value) || value['presignedUrls'] === undefined) return false;
    return true;
}

export function CollectionFilePresignedUrlsResponseFromJSON(json: any): CollectionFilePresignedUrlsResponse {
    return CollectionFilePresignedUrlsResponseFromJSONTyped(json, false);
}

export function CollectionFilePresignedUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFilePresignedUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presignedUrls': json['presigned_urls'],
    };
}

export function CollectionFilePresignedUrlsResponseToJSON(json: any): CollectionFilePresignedUrlsResponse {
    return CollectionFilePresignedUrlsResponseToJSONTyped(json, false);
}

export function CollectionFilePresignedUrlsResponseToJSONTyped(value?: CollectionFilePresignedUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presigned_urls': value['presignedUrls'],
    };
}

