/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enumeration of possible statuses for individual files within a collection.
 * 
 * Tracks the evaluation state of each file as it's processed against item criteria,
 * indicating whether the file is relevant, should be ignored, or requires manual review.
 * @export
 */
export const CollectionFileStatus = {
    Pending: 'Pending',
    Assessing: 'Assessing',
    Relevant: 'Relevant',
    Ignored: 'Ignored',
    NeedsReview: 'Needs Review',
    Error: 'Error'
} as const;
export type CollectionFileStatus = typeof CollectionFileStatus[keyof typeof CollectionFileStatus];


export function instanceOfCollectionFileStatus(value: any): boolean {
    for (const key in CollectionFileStatus) {
        if (Object.prototype.hasOwnProperty.call(CollectionFileStatus, key)) {
            if (CollectionFileStatus[key as keyof typeof CollectionFileStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CollectionFileStatusFromJSON(json: any): CollectionFileStatus {
    return CollectionFileStatusFromJSONTyped(json, false);
}

export function CollectionFileStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFileStatus {
    return json as CollectionFileStatus;
}

export function CollectionFileStatusToJSON(value?: CollectionFileStatus | null): any {
    return value as any;
}

export function CollectionFileStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CollectionFileStatus {
    return value as CollectionFileStatus;
}

