/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesResponse
 */
export interface CoordinatesResponse {
    /**
     * 
     * @type {number}
     * @memberof CoordinatesResponse
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesResponse
     */
    longitude: number;
}

/**
 * Check if a given object implements the CoordinatesResponse interface.
 */
export function instanceOfCoordinatesResponse(value: object): value is CoordinatesResponse {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function CoordinatesResponseFromJSON(json: any): CoordinatesResponse {
    return CoordinatesResponseFromJSONTyped(json, false);
}

export function CoordinatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function CoordinatesResponseToJSON(json: any): CoordinatesResponse {
    return CoordinatesResponseToJSONTyped(json, false);
}

export function CoordinatesResponseToJSONTyped(value?: CoordinatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

