/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesRequest
 */
export interface CoordinatesRequest {
    /**
     * 
     * @type {string}
     * @memberof CoordinatesRequest
     */
    address: string;
}

/**
 * Check if a given object implements the CoordinatesRequest interface.
 */
export function instanceOfCoordinatesRequest(value: object): value is CoordinatesRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function CoordinatesRequestFromJSON(json: any): CoordinatesRequest {
    return CoordinatesRequestFromJSONTyped(json, false);
}

export function CoordinatesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function CoordinatesRequestToJSON(json: any): CoordinatesRequest {
    return CoordinatesRequestToJSONTyped(json, false);
}

export function CoordinatesRequestToJSONTyped(value?: CoordinatesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
    };
}

