/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerificationJob } from './VerificationJob';
import {
    VerificationJobFromJSON,
    VerificationJobFromJSONTyped,
    VerificationJobToJSON,
    VerificationJobToJSONTyped,
} from './VerificationJob';

/**
 * Response model for creating a verification job.
 * @export
 * @interface CreateVerificationJobResponse
 */
export interface CreateVerificationJobResponse {
    /**
     * 
     * @type {VerificationJob}
     * @memberof CreateVerificationJobResponse
     */
    verificationJob: VerificationJob;
}

/**
 * Check if a given object implements the CreateVerificationJobResponse interface.
 */
export function instanceOfCreateVerificationJobResponse(value: object): value is CreateVerificationJobResponse {
    if (!('verificationJob' in value) || value['verificationJob'] === undefined) return false;
    return true;
}

export function CreateVerificationJobResponseFromJSON(json: any): CreateVerificationJobResponse {
    return CreateVerificationJobResponseFromJSONTyped(json, false);
}

export function CreateVerificationJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVerificationJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationJob': VerificationJobFromJSON(json['verification_job']),
    };
}

export function CreateVerificationJobResponseToJSON(json: any): CreateVerificationJobResponse {
    return CreateVerificationJobResponseToJSONTyped(json, false);
}

export function CreateVerificationJobResponseToJSONTyped(value?: CreateVerificationJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_job': VerificationJobToJSON(value['verificationJob']),
    };
}

