/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelFilteringRule } from './LabelFilteringRule';
import {
    LabelFilteringRuleFromJSON,
    LabelFilteringRuleFromJSONTyped,
    LabelFilteringRuleToJSON,
    LabelFilteringRuleToJSONTyped,
} from './LabelFilteringRule';
import type { DescriptionFilteringRule } from './DescriptionFilteringRule';
import {
    DescriptionFilteringRuleFromJSON,
    DescriptionFilteringRuleFromJSONTyped,
    DescriptionFilteringRuleToJSON,
    DescriptionFilteringRuleToJSONTyped,
} from './DescriptionFilteringRule';

/**
 * Request model for creating a new item.
 * @export
 * @interface CreateItemRequest
 */
export interface CreateItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateItemRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateItemRequest
     */
    description: string;
    /**
     * 
     * @type {Array<LabelFilteringRule>}
     * @memberof CreateItemRequest
     */
    labelFilteringRules?: Array<LabelFilteringRule>;
    /**
     * 
     * @type {Array<DescriptionFilteringRule>}
     * @memberof CreateItemRequest
     */
    descriptionFilteringRules?: Array<DescriptionFilteringRule> | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemRequest
     */
    clusterNumber?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateItemRequest
     */
    agentIds?: Array<string> | null;
}

/**
 * Check if a given object implements the CreateItemRequest interface.
 */
export function instanceOfCreateItemRequest(value: object): value is CreateItemRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateItemRequestFromJSON(json: any): CreateItemRequest {
    return CreateItemRequestFromJSONTyped(json, false);
}

export function CreateItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'labelFilteringRules': json['label_filtering_rules'] == null ? undefined : ((json['label_filtering_rules'] as Array<any>).map(LabelFilteringRuleFromJSON)),
        'descriptionFilteringRules': json['description_filtering_rules'] == null ? undefined : ((json['description_filtering_rules'] as Array<any>).map(DescriptionFilteringRuleFromJSON)),
        'clusterNumber': json['cluster_number'] == null ? undefined : json['cluster_number'],
        'agentIds': json['agent_ids'] == null ? undefined : json['agent_ids'],
    };
}

export function CreateItemRequestToJSON(json: any): CreateItemRequest {
    return CreateItemRequestToJSONTyped(json, false);
}

export function CreateItemRequestToJSONTyped(value?: CreateItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'label_filtering_rules': value['labelFilteringRules'] == null ? undefined : ((value['labelFilteringRules'] as Array<any>).map(LabelFilteringRuleToJSON)),
        'description_filtering_rules': value['descriptionFilteringRules'] == null ? undefined : ((value['descriptionFilteringRules'] as Array<any>).map(DescriptionFilteringRuleToJSON)),
        'cluster_number': value['clusterNumber'],
        'agent_ids': value['agentIds'],
    };
}

