/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating an agent.
 * @export
 * @interface CreateAgentRequest
 */
export interface CreateAgentRequest {
    /**
     * Name of the agent
     * @type {string}
     * @memberof CreateAgentRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    description?: string | null;
    /**
     * Prompt for the agent
     * @type {string}
     * @memberof CreateAgentRequest
     */
    prompt: string;
    /**
     * Type of the agent (Knowledge Base or REST API)
     * @type {string}
     * @memberof CreateAgentRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    knowledgeBaseId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    apiEndpoint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    athenaDatabase: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRequest
     */
    athenaQuery: string | null;
}

/**
 * Check if a given object implements the CreateAgentRequest interface.
 */
export function instanceOfCreateAgentRequest(value: object): value is CreateAgentRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('athenaDatabase' in value) || value['athenaDatabase'] === undefined) return false;
    if (!('athenaQuery' in value) || value['athenaQuery'] === undefined) return false;
    return true;
}

export function CreateAgentRequestFromJSON(json: any): CreateAgentRequest {
    return CreateAgentRequestFromJSONTyped(json, false);
}

export function CreateAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'prompt': json['prompt'],
        'type': json['type'],
        'knowledgeBaseId': json['knowledge_base_id'] == null ? undefined : json['knowledge_base_id'],
        'apiEndpoint': json['api_endpoint'] == null ? undefined : json['api_endpoint'],
        'athenaDatabase': json['athena_database'],
        'athenaQuery': json['athena_query'],
    };
}

export function CreateAgentRequestToJSON(json: any): CreateAgentRequest {
    return CreateAgentRequestToJSONTyped(json, false);
}

export function CreateAgentRequestToJSONTyped(value?: CreateAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'prompt': value['prompt'],
        'type': value['type'],
        'knowledge_base_id': value['knowledgeBaseId'],
        'api_endpoint': value['apiEndpoint'],
        'athena_database': value['athenaDatabase'],
        'athena_query': value['athenaQuery'],
    };
}

