/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * Response model for collection creation.
 * 
 * Returns the newly created collection with its assigned ID and
 * any system-generated metadata.
 * @export
 * @interface CreateCollectionResponse
 */
export interface CreateCollectionResponse {
    /**
     * 
     * @type {Collection}
     * @memberof CreateCollectionResponse
     */
    collection: Collection;
}

/**
 * Check if a given object implements the CreateCollectionResponse interface.
 */
export function instanceOfCreateCollectionResponse(value: object): value is CreateCollectionResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function CreateCollectionResponseFromJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseFromJSONTyped(json, false);
}

export function CreateCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': CollectionFromJSON(json['collection']),
    };
}

export function CreateCollectionResponseToJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseToJSONTyped(json, false);
}

export function CreateCollectionResponseToJSONTyped(value?: CreateCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionToJSON(value['collection']),
    };
}

