/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssessmentStatus } from './AssessmentStatus';
import {
    AssessmentStatusFromJSON,
    AssessmentStatusFromJSONTyped,
    AssessmentStatusToJSON,
    AssessmentStatusToJSONTyped,
} from './AssessmentStatus';

/**
 * Request model for creating a verification job.
 * @export
 * @interface CreateVerificationJobRequest
 */
export interface CreateVerificationJobRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateVerificationJobRequest
     */
    collectionId: string;
    /**
     * 
     * @type {AssessmentStatus}
     * @memberof CreateVerificationJobRequest
     */
    status?: AssessmentStatus;
    /**
     * 
     * @type {number}
     * @memberof CreateVerificationJobRequest
     */
    confidence?: number | null;
    /**
     * Whether to search the internet for additional information during verification
     * @type {boolean}
     * @memberof CreateVerificationJobRequest
     */
    searchInternet?: boolean;
}



/**
 * Check if a given object implements the CreateVerificationJobRequest interface.
 */
export function instanceOfCreateVerificationJobRequest(value: object): value is CreateVerificationJobRequest {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    return true;
}

export function CreateVerificationJobRequestFromJSON(json: any): CreateVerificationJobRequest {
    return CreateVerificationJobRequestFromJSONTyped(json, false);
}

export function CreateVerificationJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVerificationJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collection_id'],
        'status': json['status'] == null ? undefined : AssessmentStatusFromJSON(json['status']),
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'searchInternet': json['search_internet'] == null ? undefined : json['search_internet'],
    };
}

export function CreateVerificationJobRequestToJSON(json: any): CreateVerificationJobRequest {
    return CreateVerificationJobRequestToJSONTyped(json, false);
}

export function CreateVerificationJobRequestToJSONTyped(value?: CreateVerificationJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_id': value['collectionId'],
        'status': AssessmentStatusToJSON(value['status']),
        'confidence': value['confidence'],
        'search_internet': value['searchInternet'],
    };
}

