/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for generating multiple presigned upload URLs.
 * 
 * Takes a list of filenames and generates corresponding presigned URLs
 * for batch file upload operations to S3 storage.
 * @export
 * @interface GenerateUploadUrlsRequest
 */
export interface GenerateUploadUrlsRequest {
    /**
     * List of filenames for which to generate presigned URLs
     * @type {Array<string>}
     * @memberof GenerateUploadUrlsRequest
     */
    filenames: Array<string>;
}

/**
 * Check if a given object implements the GenerateUploadUrlsRequest interface.
 */
export function instanceOfGenerateUploadUrlsRequest(value: object): value is GenerateUploadUrlsRequest {
    if (!('filenames' in value) || value['filenames'] === undefined) return false;
    return true;
}

export function GenerateUploadUrlsRequestFromJSON(json: any): GenerateUploadUrlsRequest {
    return GenerateUploadUrlsRequestFromJSONTyped(json, false);
}

export function GenerateUploadUrlsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateUploadUrlsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filenames': json['filenames'],
    };
}

export function GenerateUploadUrlsRequestToJSON(json: any): GenerateUploadUrlsRequest {
    return GenerateUploadUrlsRequestToJSONTyped(json, false);
}

export function GenerateUploadUrlsRequestToJSONTyped(value?: GenerateUploadUrlsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filenames': value['filenames'],
    };
}

