/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PresignedFileUrl } from './PresignedFileUrl';
import {
    PresignedFileUrlFromJSON,
    PresignedFileUrlFromJSONTyped,
    PresignedFileUrlToJSON,
    PresignedFileUrlToJSONTyped,
} from './PresignedFileUrl';

/**
 * Response model containing multiple presigned upload URLs.
 * 
 * Returns a list of presigned URLs with their corresponding filenames
 * and S3 keys for batch file upload operations.
 * @export
 * @interface GenerateUploadUrlsResponse
 */
export interface GenerateUploadUrlsResponse {
    /**
     * List of presigned URLs for file uploads
     * @type {Array<PresignedFileUrl>}
     * @memberof GenerateUploadUrlsResponse
     */
    urls: Array<PresignedFileUrl>;
}

/**
 * Check if a given object implements the GenerateUploadUrlsResponse interface.
 */
export function instanceOfGenerateUploadUrlsResponse(value: object): value is GenerateUploadUrlsResponse {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function GenerateUploadUrlsResponseFromJSON(json: any): GenerateUploadUrlsResponse {
    return GenerateUploadUrlsResponseFromJSONTyped(json, false);
}

export function GenerateUploadUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateUploadUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': ((json['urls'] as Array<any>).map(PresignedFileUrlFromJSON)),
    };
}

export function GenerateUploadUrlsResponseToJSON(json: any): GenerateUploadUrlsResponse {
    return GenerateUploadUrlsResponseToJSONTyped(json, false);
}

export function GenerateUploadUrlsResponseToJSONTyped(value?: GenerateUploadUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': ((value['urls'] as Array<any>).map(PresignedFileUrlToJSON)),
    };
}

