/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
    ItemToJSONTyped,
} from './Item';

/**
 * Response model for listing items.
 * 
 * Returns a paginated list of Item objects that match the query criteria.
 * @export
 * @interface ItemListResponse
 */
export interface ItemListResponse {
    /**
     * 
     * @type {Array<Item>}
     * @memberof ItemListResponse
     */
    items: Array<Item>;
}

/**
 * Check if a given object implements the ItemListResponse interface.
 */
export function instanceOfItemListResponse(value: object): value is ItemListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ItemListResponseFromJSON(json: any): ItemListResponse {
    return ItemListResponseFromJSONTyped(json, false);
}

export function ItemListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ItemFromJSON)),
    };
}

export function ItemListResponseToJSON(json: any): ItemListResponse {
    return ItemListResponseToJSONTyped(json, false);
}

export function ItemListResponseToJSONTyped(value?: ItemListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ItemToJSON)),
    };
}

