/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelIdRequest
 */
export interface ModelIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelIdRequest
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof ModelIdRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ModelIdRequest interface.
 */
export function instanceOfModelIdRequest(value: object): value is ModelIdRequest {
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    return true;
}

export function ModelIdRequestFromJSON(json: any): ModelIdRequest {
    return ModelIdRequestFromJSONTyped(json, false);
}

export function ModelIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['model_id'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ModelIdRequestToJSON(json: any): ModelIdRequest {
    return ModelIdRequestToJSONTyped(json, false);
}

export function ModelIdRequestToJSONTyped(value?: ModelIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_id': value['modelId'],
        'description': value['description'],
    };
}

