/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model representing a single presigned URL for file upload.
 * 
 * Contains the mapping between a filename, its S3 storage key,
 * and the temporary presigned URL for direct upload access.
 * @export
 * @interface PresignedFileUrl
 */
export interface PresignedFileUrl {
    /**
     * Name of the file
     * @type {string}
     * @memberof PresignedFileUrl
     */
    filename: string;
    /**
     * S3 key for the file
     * @type {string}
     * @memberof PresignedFileUrl
     */
    s3Key: string;
    /**
     * Presigned URL for file upload
     * @type {string}
     * @memberof PresignedFileUrl
     */
    presignedUrl: string;
}

/**
 * Check if a given object implements the PresignedFileUrl interface.
 */
export function instanceOfPresignedFileUrl(value: object): value is PresignedFileUrl {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    return true;
}

export function PresignedFileUrlFromJSON(json: any): PresignedFileUrl {
    return PresignedFileUrlFromJSONTyped(json, false);
}

export function PresignedFileUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedFileUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        's3Key': json['s3_key'],
        'presignedUrl': json['presigned_url'],
    };
}

export function PresignedFileUrlToJSON(json: any): PresignedFileUrl {
    return PresignedFileUrlToJSONTyped(json, false);
}

export function PresignedFileUrlToJSONTyped(value?: PresignedFileUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        's3_key': value['s3Key'],
        'presigned_url': value['presignedUrl'],
    };
}

