/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for generating a presigned URL for file upload.
 * @export
 * @interface PresignUploadResponse
 */
export interface PresignUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof PresignUploadResponse
     */
    presignedUrl: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PresignUploadResponse
     */
    fileMetadata: { [key: string]: any; };
}

/**
 * Check if a given object implements the PresignUploadResponse interface.
 */
export function instanceOfPresignUploadResponse(value: object): value is PresignUploadResponse {
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    if (!('fileMetadata' in value) || value['fileMetadata'] === undefined) return false;
    return true;
}

export function PresignUploadResponseFromJSON(json: any): PresignUploadResponse {
    return PresignUploadResponseFromJSONTyped(json, false);
}

export function PresignUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presignedUrl': json['presigned_url'],
        'fileMetadata': json['file_metadata'],
    };
}

export function PresignUploadResponseToJSON(json: any): PresignUploadResponse {
    return PresignUploadResponseToJSONTyped(json, false);
}

export function PresignUploadResponseToJSONTyped(value?: PresignUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presigned_url': value['presignedUrl'],
        'file_metadata': value['fileMetadata'],
    };
}

