/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemPromptRequest
 */
export interface SystemPromptRequest {
    /**
     * 
     * @type {string}
     * @memberof SystemPromptRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SystemPromptRequest interface.
 */
export function instanceOfSystemPromptRequest(value: object): value is SystemPromptRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function SystemPromptRequestFromJSON(json: any): SystemPromptRequest {
    return SystemPromptRequestFromJSONTyped(json, false);
}

export function SystemPromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemPromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SystemPromptRequestToJSON(json: any): SystemPromptRequest {
    return SystemPromptRequestToJSONTyped(json, false);
}

export function SystemPromptRequestToJSONTyped(value?: SystemPromptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'description': value['description'],
    };
}

