/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestLabelFilteringRuleLabel } from './TestLabelFilteringRuleLabel';
import {
    TestLabelFilteringRuleLabelFromJSON,
    TestLabelFilteringRuleLabelFromJSONTyped,
    TestLabelFilteringRuleLabelToJSON,
    TestLabelFilteringRuleLabelToJSONTyped,
} from './TestLabelFilteringRuleLabel';

/**
 * Response model for testing label filtering prompt.
 * @export
 * @interface TestLabelFilteringRuleResponse
 */
export interface TestLabelFilteringRuleResponse {
    /**
     * Labels that were detected in the images
     * @type {Array<TestLabelFilteringRuleLabel>}
     * @memberof TestLabelFilteringRuleResponse
     */
    labels: Array<TestLabelFilteringRuleLabel>;
}

/**
 * Check if a given object implements the TestLabelFilteringRuleResponse interface.
 */
export function instanceOfTestLabelFilteringRuleResponse(value: object): value is TestLabelFilteringRuleResponse {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function TestLabelFilteringRuleResponseFromJSON(json: any): TestLabelFilteringRuleResponse {
    return TestLabelFilteringRuleResponseFromJSONTyped(json, false);
}

export function TestLabelFilteringRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestLabelFilteringRuleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': ((json['labels'] as Array<any>).map(TestLabelFilteringRuleLabelFromJSON)),
    };
}

export function TestLabelFilteringRuleResponseToJSON(json: any): TestLabelFilteringRuleResponse {
    return TestLabelFilteringRuleResponseToJSONTyped(json, false);
}

export function TestLabelFilteringRuleResponseToJSONTyped(value?: TestLabelFilteringRuleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': ((value['labels'] as Array<any>).map(TestLabelFilteringRuleLabelToJSON)),
    };
}

