/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for label detection results.
 * @export
 * @interface TestLabelFilteringRuleLabel
 */
export interface TestLabelFilteringRuleLabel {
    /**
     * Name of the detected label
     * @type {string}
     * @memberof TestLabelFilteringRuleLabel
     */
    name: string;
    /**
     * Confidence score of the label detection
     * @type {number}
     * @memberof TestLabelFilteringRuleLabel
     */
    confidence: number;
    /**
     * S3 key of the image where the label was detected
     * @type {string}
     * @memberof TestLabelFilteringRuleLabel
     */
    s3Key: string;
}

/**
 * Check if a given object implements the TestLabelFilteringRuleLabel interface.
 */
export function instanceOfTestLabelFilteringRuleLabel(value: object): value is TestLabelFilteringRuleLabel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('s3Key' in value) || value['s3Key'] === undefined) return false;
    return true;
}

export function TestLabelFilteringRuleLabelFromJSON(json: any): TestLabelFilteringRuleLabel {
    return TestLabelFilteringRuleLabelFromJSONTyped(json, false);
}

export function TestLabelFilteringRuleLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestLabelFilteringRuleLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'confidence': json['confidence'],
        's3Key': json['s3_key'],
    };
}

export function TestLabelFilteringRuleLabelToJSON(json: any): TestLabelFilteringRuleLabel {
    return TestLabelFilteringRuleLabelToJSONTyped(json, false);
}

export function TestLabelFilteringRuleLabelToJSONTyped(value?: TestLabelFilteringRuleLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'confidence': value['confidence'],
        's3_key': value['s3Key'],
    };
}

