/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for testing a label filtering rule.
 * @export
 * @interface TestLabelFilteringRuleRequest
 */
export interface TestLabelFilteringRuleRequest {
    /**
     * S3 keys for the images to test against
     * @type {Array<string>}
     * @memberof TestLabelFilteringRuleRequest
     */
    imageS3Keys: Array<string>;
}

/**
 * Check if a given object implements the TestLabelFilteringRuleRequest interface.
 */
export function instanceOfTestLabelFilteringRuleRequest(value: object): value is TestLabelFilteringRuleRequest {
    if (!('imageS3Keys' in value) || value['imageS3Keys'] === undefined) return false;
    return true;
}

export function TestLabelFilteringRuleRequestFromJSON(json: any): TestLabelFilteringRuleRequest {
    return TestLabelFilteringRuleRequestFromJSONTyped(json, false);
}

export function TestLabelFilteringRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestLabelFilteringRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageS3Keys': json['image_s3_keys'],
    };
}

export function TestLabelFilteringRuleRequestToJSON(json: any): TestLabelFilteringRuleRequest {
    return TestLabelFilteringRuleRequestToJSONTyped(json, false);
}

export function TestLabelFilteringRuleRequestToJSONTyped(value?: TestLabelFilteringRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_s3_keys': value['imageS3Keys'],
    };
}

