/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallUsingAllFilesResponse } from './CallUsingAllFilesResponse';
import {
    CallUsingAllFilesResponseFromJSON,
    CallUsingAllFilesResponseFromJSONTyped,
    CallUsingAllFilesResponseToJSON,
    CallUsingAllFilesResponseToJSONTyped,
} from './CallUsingAllFilesResponse';

/**
 * Response model for testing description filtering prompt.
 * @export
 * @interface TestDescriptionFilterPromptResponse
 */
export interface TestDescriptionFilterPromptResponse {
    /**
     * Response from the description filtering prompt test
     * @type {CallUsingAllFilesResponse}
     * @memberof TestDescriptionFilterPromptResponse
     */
    response: CallUsingAllFilesResponse;
}

/**
 * Check if a given object implements the TestDescriptionFilterPromptResponse interface.
 */
export function instanceOfTestDescriptionFilterPromptResponse(value: object): value is TestDescriptionFilterPromptResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    return true;
}

export function TestDescriptionFilterPromptResponseFromJSON(json: any): TestDescriptionFilterPromptResponse {
    return TestDescriptionFilterPromptResponseFromJSONTyped(json, false);
}

export function TestDescriptionFilterPromptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestDescriptionFilterPromptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': CallUsingAllFilesResponseFromJSON(json['response']),
    };
}

export function TestDescriptionFilterPromptResponseToJSON(json: any): TestDescriptionFilterPromptResponse {
    return TestDescriptionFilterPromptResponseToJSONTyped(json, false);
}

export function TestDescriptionFilterPromptResponseToJSONTyped(value?: TestDescriptionFilterPromptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': CallUsingAllFilesResponseToJSON(value['response']),
    };
}

