/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for testing description filtering prompt.
 * @export
 * @interface TestDescriptionFilterPromptRequest
 */
export interface TestDescriptionFilterPromptRequest {
    /**
     * Description to test against the item
     * @type {string}
     * @memberof TestDescriptionFilterPromptRequest
     */
    description: string;
    /**
     * S3 keys for the images to test against
     * @type {Array<string>}
     * @memberof TestDescriptionFilterPromptRequest
     */
    imageS3Keys: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TestDescriptionFilterPromptRequest
     */
    agentIds?: Array<string> | null;
    /**
     * Whether to search the internet for additional information during the test
     * @type {boolean}
     * @memberof TestDescriptionFilterPromptRequest
     */
    searchInternet?: boolean;
}

/**
 * Check if a given object implements the TestDescriptionFilterPromptRequest interface.
 */
export function instanceOfTestDescriptionFilterPromptRequest(value: object): value is TestDescriptionFilterPromptRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('imageS3Keys' in value) || value['imageS3Keys'] === undefined) return false;
    return true;
}

export function TestDescriptionFilterPromptRequestFromJSON(json: any): TestDescriptionFilterPromptRequest {
    return TestDescriptionFilterPromptRequestFromJSONTyped(json, false);
}

export function TestDescriptionFilterPromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestDescriptionFilterPromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'imageS3Keys': json['image_s3_keys'],
        'agentIds': json['agent_ids'] == null ? undefined : json['agent_ids'],
        'searchInternet': json['search_internet'] == null ? undefined : json['search_internet'],
    };
}

export function TestDescriptionFilterPromptRequestToJSON(json: any): TestDescriptionFilterPromptRequest {
    return TestDescriptionFilterPromptRequestToJSONTyped(json, false);
}

export function TestDescriptionFilterPromptRequestToJSONTyped(value?: TestDescriptionFilterPromptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'image_s3_keys': value['imageS3Keys'],
        'agent_ids': value['agentIds'],
        'search_internet': value['searchInternet'],
    };
}

