/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenUsage
 */
export interface TokenUsage {
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof TokenUsage
     */
    outputTokens: number;
}

/**
 * Check if a given object implements the TokenUsage interface.
 */
export function instanceOfTokenUsage(value: object): value is TokenUsage {
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    return true;
}

export function TokenUsageFromJSON(json: any): TokenUsage {
    return TokenUsageFromJSONTyped(json, false);
}

export function TokenUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'inputTokens': json['input_tokens'],
        'outputTokens': json['output_tokens'],
    };
}

export function TokenUsageToJSON(json: any): TokenUsage {
    return TokenUsageToJSONTyped(json, false);
}

export function TokenUsageToJSONTyped(value?: TokenUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
    };
}

