/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TotalCheckItemResult } from './TotalCheckItemResult';
import {
    TotalCheckItemResultFromJSON,
    TotalCheckItemResultFromJSONTyped,
    TotalCheckItemResultToJSON,
    TotalCheckItemResultToJSONTyped,
} from './TotalCheckItemResult';

/**
 * 
 * @export
 * @interface TotalCheckResponse
 */
export interface TotalCheckResponse {
    /**
     * A list of the items that are being analyzed for and their matching (or not matching) filenames 
     * @type {Array<TotalCheckItemResult>}
     * @memberof TotalCheckResponse
     */
    items: Array<TotalCheckItemResult>;
}

/**
 * Check if a given object implements the TotalCheckResponse interface.
 */
export function instanceOfTotalCheckResponse(value: object): value is TotalCheckResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TotalCheckResponseFromJSON(json: any): TotalCheckResponse {
    return TotalCheckResponseFromJSONTyped(json, false);
}

export function TotalCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TotalCheckItemResultFromJSON)),
    };
}

export function TotalCheckResponseToJSON(json: any): TotalCheckResponse {
    return TotalCheckResponseToJSONTyped(json, false);
}

export function TotalCheckResponseToJSONTyped(value?: TotalCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TotalCheckItemResultToJSON)),
    };
}

