/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for updating an agent.
 * @export
 * @interface UpdateAgentRequest
 */
export interface UpdateAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    prompt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    knowledgeBaseId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    apiEndpoint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    athenaDatabase: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    athenaQuery: string | null;
}

/**
 * Check if a given object implements the UpdateAgentRequest interface.
 */
export function instanceOfUpdateAgentRequest(value: object): value is UpdateAgentRequest {
    if (!('athenaDatabase' in value) || value['athenaDatabase'] === undefined) return false;
    if (!('athenaQuery' in value) || value['athenaQuery'] === undefined) return false;
    return true;
}

export function UpdateAgentRequestFromJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestFromJSONTyped(json, false);
}

export function UpdateAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'type': json['type'] == null ? undefined : json['type'],
        'knowledgeBaseId': json['knowledge_base_id'] == null ? undefined : json['knowledge_base_id'],
        'apiEndpoint': json['api_endpoint'] == null ? undefined : json['api_endpoint'],
        'athenaDatabase': json['athena_database'],
        'athenaQuery': json['athena_query'],
    };
}

export function UpdateAgentRequestToJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestToJSONTyped(json, false);
}

export function UpdateAgentRequestToJSONTyped(value?: UpdateAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'prompt': value['prompt'],
        'type': value['type'],
        'knowledge_base_id': value['knowledgeBaseId'],
        'api_endpoint': value['apiEndpoint'],
        'athena_database': value['athenaDatabase'],
        'athena_query': value['athenaQuery'],
    };
}

