/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssessmentStatus } from './AssessmentStatus';
import {
    AssessmentStatusFromJSON,
    AssessmentStatusFromJSONTyped,
    AssessmentStatusToJSON,
    AssessmentStatusToJSONTyped,
} from './AssessmentStatus';

/**
 * Request model for updating a verification job.
 * @export
 * @interface UpdateVerificationJobRequest
 */
export interface UpdateVerificationJobRequest {
    /**
     * 
     * @type {AssessmentStatus}
     * @memberof UpdateVerificationJobRequest
     */
    status?: AssessmentStatus | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateVerificationJobRequest
     */
    confidence?: number | null;
    /**
     * Whether to search the internet for additional information during verification
     * @type {boolean}
     * @memberof UpdateVerificationJobRequest
     */
    searchInternet?: boolean;
}



/**
 * Check if a given object implements the UpdateVerificationJobRequest interface.
 */
export function instanceOfUpdateVerificationJobRequest(value: object): value is UpdateVerificationJobRequest {
    return true;
}

export function UpdateVerificationJobRequestFromJSON(json: any): UpdateVerificationJobRequest {
    return UpdateVerificationJobRequestFromJSONTyped(json, false);
}

export function UpdateVerificationJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVerificationJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : AssessmentStatusFromJSON(json['status']),
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'searchInternet': json['search_internet'] == null ? undefined : json['search_internet'],
    };
}

export function UpdateVerificationJobRequestToJSON(json: any): UpdateVerificationJobRequest {
    return UpdateVerificationJobRequestToJSONTyped(json, false);
}

export function UpdateVerificationJobRequestToJSONTyped(value?: UpdateVerificationJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': AssessmentStatusToJSON(value['status']),
        'confidence': value['confidence'],
        'search_internet': value['searchInternet'],
    };
}

