/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * Response model for collection updates.
 * 
 * Returns the updated collection with all current values after
 * the modification has been applied.
 * @export
 * @interface UpdateCollectionResponse
 */
export interface UpdateCollectionResponse {
    /**
     * 
     * @type {Collection}
     * @memberof UpdateCollectionResponse
     */
    collection: Collection;
}

/**
 * Check if a given object implements the UpdateCollectionResponse interface.
 */
export function instanceOfUpdateCollectionResponse(value: object): value is UpdateCollectionResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function UpdateCollectionResponseFromJSON(json: any): UpdateCollectionResponse {
    return UpdateCollectionResponseFromJSONTyped(json, false);
}

export function UpdateCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': CollectionFromJSON(json['collection']),
    };
}

export function UpdateCollectionResponseToJSON(json: any): UpdateCollectionResponse {
    return UpdateCollectionResponseToJSONTyped(json, false);
}

export function UpdateCollectionResponseToJSONTyped(value?: UpdateCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionToJSON(value['collection']),
    };
}

