/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerificationJob } from './VerificationJob';
import {
    VerificationJobFromJSON,
    VerificationJobFromJSONTyped,
    VerificationJobToJSON,
    VerificationJobToJSONTyped,
} from './VerificationJob';

/**
 * Response model for updating a verification job.
 * @export
 * @interface UpdateVerificationJobResponse
 */
export interface UpdateVerificationJobResponse {
    /**
     * 
     * @type {VerificationJob}
     * @memberof UpdateVerificationJobResponse
     */
    verificationJob: VerificationJob;
}

/**
 * Check if a given object implements the UpdateVerificationJobResponse interface.
 */
export function instanceOfUpdateVerificationJobResponse(value: object): value is UpdateVerificationJobResponse {
    if (!('verificationJob' in value) || value['verificationJob'] === undefined) return false;
    return true;
}

export function UpdateVerificationJobResponseFromJSON(json: any): UpdateVerificationJobResponse {
    return UpdateVerificationJobResponseFromJSONTyped(json, false);
}

export function UpdateVerificationJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVerificationJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationJob': VerificationJobFromJSON(json['verification_job']),
    };
}

export function UpdateVerificationJobResponseToJSON(json: any): UpdateVerificationJobResponse {
    return UpdateVerificationJobResponseToJSONTyped(json, false);
}

export function UpdateVerificationJobResponseToJSONTyped(value?: UpdateVerificationJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_job': VerificationJobToJSON(value['verificationJob']),
    };
}

