/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelFilteringRule } from './LabelFilteringRule';
import {
    LabelFilteringRuleFromJSON,
    LabelFilteringRuleFromJSONTyped,
    LabelFilteringRuleToJSON,
    LabelFilteringRuleToJSONTyped,
} from './LabelFilteringRule';
import type { DescriptionFilteringRule } from './DescriptionFilteringRule';
import {
    DescriptionFilteringRuleFromJSON,
    DescriptionFilteringRuleFromJSONTyped,
    DescriptionFilteringRuleToJSON,
    DescriptionFilteringRuleToJSONTyped,
} from './DescriptionFilteringRule';

/**
 * Request model for updating an existing item.
 * @export
 * @interface UpdateItemRequest
 */
export interface UpdateItemRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateItemRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateItemRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<LabelFilteringRule>}
     * @memberof UpdateItemRequest
     */
    labelFilteringRules?: Array<LabelFilteringRule> | null;
    /**
     * 
     * @type {Array<DescriptionFilteringRule>}
     * @memberof UpdateItemRequest
     */
    descriptionFilteringRules?: Array<DescriptionFilteringRule> | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateItemRequest
     */
    clusterNumber?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateItemRequest
     */
    agentIds?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdateItemRequest interface.
 */
export function instanceOfUpdateItemRequest(value: object): value is UpdateItemRequest {
    return true;
}

export function UpdateItemRequestFromJSON(json: any): UpdateItemRequest {
    return UpdateItemRequestFromJSONTyped(json, false);
}

export function UpdateItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'labelFilteringRules': json['label_filtering_rules'] == null ? undefined : ((json['label_filtering_rules'] as Array<any>).map(LabelFilteringRuleFromJSON)),
        'descriptionFilteringRules': json['description_filtering_rules'] == null ? undefined : ((json['description_filtering_rules'] as Array<any>).map(DescriptionFilteringRuleFromJSON)),
        'clusterNumber': json['cluster_number'] == null ? undefined : json['cluster_number'],
        'agentIds': json['agent_ids'] == null ? undefined : json['agent_ids'],
    };
}

export function UpdateItemRequestToJSON(json: any): UpdateItemRequest {
    return UpdateItemRequestToJSONTyped(json, false);
}

export function UpdateItemRequestToJSONTyped(value?: UpdateItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'label_filtering_rules': value['labelFilteringRules'] == null ? undefined : ((value['labelFilteringRules'] as Array<any>).map(LabelFilteringRuleToJSON)),
        'description_filtering_rules': value['descriptionFilteringRules'] == null ? undefined : ((value['descriptionFilteringRules'] as Array<any>).map(DescriptionFilteringRuleToJSON)),
        'cluster_number': value['clusterNumber'],
        'agent_ids': value['agentIds'],
    };
}

