/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerificationJobDto } from './VerificationJobDto';
import {
    VerificationJobDtoFromJSON,
    VerificationJobDtoFromJSONTyped,
    VerificationJobDtoToJSON,
    VerificationJobDtoToJSONTyped,
} from './VerificationJobDto';

/**
 * Response model for retrieving a single verification job.
 * @export
 * @interface VerificationJobResponse
 */
export interface VerificationJobResponse {
    /**
     * 
     * @type {VerificationJobDto}
     * @memberof VerificationJobResponse
     */
    verificationJob: VerificationJobDto;
}

/**
 * Check if a given object implements the VerificationJobResponse interface.
 */
export function instanceOfVerificationJobResponse(value: object): value is VerificationJobResponse {
    if (!('verificationJob' in value) || value['verificationJob'] === undefined) return false;
    return true;
}

export function VerificationJobResponseFromJSON(json: any): VerificationJobResponse {
    return VerificationJobResponseFromJSONTyped(json, false);
}

export function VerificationJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationJob': VerificationJobDtoFromJSON(json['verification_job']),
    };
}

export function VerificationJobResponseToJSON(json: any): VerificationJobResponse {
    return VerificationJobResponseToJSONTyped(json, false);
}

export function VerificationJobResponseToJSONTyped(value?: VerificationJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_job': VerificationJobDtoToJSON(value['verificationJob']),
    };
}

