/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a log entry for verification job execution tracking.
 * 
 * Stores timestamped log messages with severity levels to track
 * the progress and issues during verification job processing.
 * @export
 * @interface VerificationJobLogEntry
 */
export interface VerificationJobLogEntry {
    /**
     * 
     * @type {string}
     * @memberof VerificationJobLogEntry
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobLogEntry
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobLogEntry
     */
    verificationJobId: string;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobLogEntry
     */
    level: string;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobLogEntry
     */
    message: string;
}

/**
 * Check if a given object implements the VerificationJobLogEntry interface.
 */
export function instanceOfVerificationJobLogEntry(value: object): value is VerificationJobLogEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('verificationJobId' in value) || value['verificationJobId'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function VerificationJobLogEntryFromJSON(json: any): VerificationJobLogEntry {
    return VerificationJobLogEntryFromJSONTyped(json, false);
}

export function VerificationJobLogEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobLogEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'verificationJobId': json['verification_job_id'],
        'level': json['level'],
        'message': json['message'],
    };
}

export function VerificationJobLogEntryToJSON(json: any): VerificationJobLogEntry {
    return VerificationJobLogEntryToJSONTyped(json, false);
}

export function VerificationJobLogEntryToJSONTyped(value?: VerificationJobLogEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'verification_job_id': value['verificationJobId'],
        'level': value['level'],
        'message': value['message'],
    };
}

