/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerificationJobLogEntry } from './VerificationJobLogEntry';
import {
    VerificationJobLogEntryFromJSON,
    VerificationJobLogEntryFromJSONTyped,
    VerificationJobLogEntryToJSON,
    VerificationJobLogEntryToJSONTyped,
} from './VerificationJobLogEntry';

/**
 * Response model for listing verification job log entries with pagination.
 * @export
 * @interface VerificationJobLogListResponse
 */
export interface VerificationJobLogListResponse {
    /**
     * 
     * @type {Array<VerificationJobLogEntry>}
     * @memberof VerificationJobLogListResponse
     */
    items: Array<VerificationJobLogEntry>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VerificationJobLogListResponse
     */
    lastEvaluatedKey?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the VerificationJobLogListResponse interface.
 */
export function instanceOfVerificationJobLogListResponse(value: object): value is VerificationJobLogListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function VerificationJobLogListResponseFromJSON(json: any): VerificationJobLogListResponse {
    return VerificationJobLogListResponseFromJSONTyped(json, false);
}

export function VerificationJobLogListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobLogListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(VerificationJobLogEntryFromJSON)),
        'lastEvaluatedKey': json['last_evaluated_key'] == null ? undefined : json['last_evaluated_key'],
    };
}

export function VerificationJobLogListResponseToJSON(json: any): VerificationJobLogListResponse {
    return VerificationJobLogListResponseToJSONTyped(json, false);
}

export function VerificationJobLogListResponseToJSONTyped(value?: VerificationJobLogListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(VerificationJobLogEntryToJSON)),
        'last_evaluated_key': value['lastEvaluatedKey'],
    };
}

