/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerificationJobSecondPassRequest
 */
export interface VerificationJobSecondPassRequest {
    /**
     * 
     * @type {boolean}
     * @memberof VerificationJobSecondPassRequest
     */
    secondPass: boolean;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobSecondPassRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the VerificationJobSecondPassRequest interface.
 */
export function instanceOfVerificationJobSecondPassRequest(value: object): value is VerificationJobSecondPassRequest {
    if (!('secondPass' in value) || value['secondPass'] === undefined) return false;
    return true;
}

export function VerificationJobSecondPassRequestFromJSON(json: any): VerificationJobSecondPassRequest {
    return VerificationJobSecondPassRequestFromJSONTyped(json, false);
}

export function VerificationJobSecondPassRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobSecondPassRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'secondPass': json['second_pass'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function VerificationJobSecondPassRequestToJSON(json: any): VerificationJobSecondPassRequest {
    return VerificationJobSecondPassRequestToJSONTyped(json, false);
}

export function VerificationJobSecondPassRequestToJSONTyped(value?: VerificationJobSecondPassRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'second_pass': value['secondPass'],
        'description': value['description'],
    };
}

