/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssessmentStatus } from './AssessmentStatus';
import {
    AssessmentStatusFromJSON,
    AssessmentStatusFromJSONTyped,
    AssessmentStatusToJSON,
    AssessmentStatusToJSONTyped,
} from './AssessmentStatus';
import type { CollectionFileInstance } from './CollectionFileInstance';
import {
    CollectionFileInstanceFromJSON,
    CollectionFileInstanceFromJSONTyped,
    CollectionFileInstanceToJSON,
    CollectionFileInstanceToJSONTyped,
} from './CollectionFileInstance';
import type { ItemInstance } from './ItemInstance';
import {
    ItemInstanceFromJSON,
    ItemInstanceFromJSONTyped,
    ItemInstanceToJSON,
    ItemInstanceToJSONTyped,
} from './ItemInstance';

/**
 * Data Transfer Object for verification jobs with additional display information.
 * 
 * Extends VerificationJob with additional fields for UI presentation,
 * including collection name and total cost calculations.
 * @export
 * @interface VerificationJobDto
 */
export interface VerificationJobDto {
    /**
     * 
     * @type {string}
     * @memberof VerificationJobDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobDto
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobDto
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobDto
     */
    collectionId: string;
    /**
     * 
     * @type {AssessmentStatus}
     * @memberof VerificationJobDto
     */
    status?: AssessmentStatus;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobDto
     */
    confidence?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobDto
     */
    aggregatedResults?: string | null;
    /**
     * 
     * @type {Array<ItemInstance>}
     * @memberof VerificationJobDto
     */
    items?: Array<ItemInstance>;
    /**
     * 
     * @type {Array<CollectionFileInstance>}
     * @memberof VerificationJobDto
     */
    files?: Array<CollectionFileInstance>;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobDto
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobDto
     */
    cost?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof VerificationJobDto
     */
    searchInternet?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VerificationJobDto
     */
    collectionName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VerificationJobDto
     */
    totalCost?: number | null;
}



/**
 * Check if a given object implements the VerificationJobDto interface.
 */
export function instanceOfVerificationJobDto(value: object): value is VerificationJobDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    return true;
}

export function VerificationJobDtoFromJSON(json: any): VerificationJobDto {
    return VerificationJobDtoFromJSONTyped(json, false);
}

export function VerificationJobDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'collectionId': json['collection_id'],
        'status': json['status'] == null ? undefined : AssessmentStatusFromJSON(json['status']),
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'aggregatedResults': json['aggregated_results'] == null ? undefined : json['aggregated_results'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ItemInstanceFromJSON)),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(CollectionFileInstanceFromJSON)),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'searchInternet': json['search_internet'] == null ? undefined : json['search_internet'],
        'collectionName': json['collection_name'] == null ? undefined : json['collection_name'],
        'totalCost': json['total_cost'] == null ? undefined : json['total_cost'],
    };
}

export function VerificationJobDtoToJSON(json: any): VerificationJobDto {
    return VerificationJobDtoToJSONTyped(json, false);
}

export function VerificationJobDtoToJSONTyped(value?: VerificationJobDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'collection_id': value['collectionId'],
        'status': AssessmentStatusToJSON(value['status']),
        'confidence': value['confidence'],
        'aggregated_results': value['aggregatedResults'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ItemInstanceToJSON)),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(CollectionFileInstanceToJSON)),
        'error_message': value['errorMessage'],
        'cost': value['cost'],
        'search_internet': value['searchInternet'],
        'collection_name': value['collectionName'],
        'total_cost': value['totalCost'],
    };
}

