/* tslint:disable */
/* eslint-disable */
/**
 * Computer Vision Image Verification API
 * FastAPI backend for the Computer Vision Image Verification sample.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model containing presigned URLs for verification job files.
 * @export
 * @interface VerificationJobFilePresignedUrlsResponse
 */
export interface VerificationJobFilePresignedUrlsResponse {
    /**
     * Dictionary mapping file IDs to their presigned GET URLs
     * @type {{ [key: string]: string; }}
     * @memberof VerificationJobFilePresignedUrlsResponse
     */
    presignedUrls: { [key: string]: string; };
}

/**
 * Check if a given object implements the VerificationJobFilePresignedUrlsResponse interface.
 */
export function instanceOfVerificationJobFilePresignedUrlsResponse(value: object): value is VerificationJobFilePresignedUrlsResponse {
    if (!('presignedUrls' in value) || value['presignedUrls'] === undefined) return false;
    return true;
}

export function VerificationJobFilePresignedUrlsResponseFromJSON(json: any): VerificationJobFilePresignedUrlsResponse {
    return VerificationJobFilePresignedUrlsResponseFromJSONTyped(json, false);
}

export function VerificationJobFilePresignedUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationJobFilePresignedUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presignedUrls': json['presigned_urls'],
    };
}

export function VerificationJobFilePresignedUrlsResponseToJSON(json: any): VerificationJobFilePresignedUrlsResponse {
    return VerificationJobFilePresignedUrlsResponseToJSONTyped(json, false);
}

export function VerificationJobFilePresignedUrlsResponseToJSONTyped(value?: VerificationJobFilePresignedUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presigned_urls': value['presignedUrls'],
    };
}

